apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
spec:
  initContainers:
    - name: init-sleep
      image: busybox:latest
      command: ["sh", "-c", "sleep 10"]
  containers:
    - name: nginx
      image: nginx:latest
