apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-test
spec:
  template:
    spec:
      containers:
        - name: pg-test
          command:
            - sh
            - -c
            - >
              psql -h dev-postgresql -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT NOW()" && sleep 600