# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ckad-training
networking:
  #disableDefaultCNI: true
  podSubnet: "100.64.0.0/10"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/kind-data/control-plane
        containerPath: /mnt/data
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authorization-mode: "AlwaysAllow"
  - role: worker
    extraMounts:
      - hostPath: /tmp/kind-data/worker
        containerPath: /mnt/dat
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "type=worker"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
