#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - |
    # Install Docker
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
      https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli

  - |
    # Install kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm kubectl

  - |
    # Install kind
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-arm64
    chmod +x ./kind
    mv ./kind /usr/local/bin/kind

  - |
    # Install Helm
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  - |
    # Set alias for kubectl to k for root user
    echo 'alias k="kubectl"' >> /root/.bashrc

  - |
    # Clone the git repository
    git clone https://github.com/enact-it/ckad-training.git /root/ckad-training

final_message: "✅ Cloud-init complete. Kind + Docker + kubectl + Helm are installed."

