apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: secret
