apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
