apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/tmp/data"
          name: hostpath-pv
  volumes:
    - name: hostpath-pv
      persistentVolumeClaim:
        claimName: hostpath-pvc
